### ISSUE TITLE
prepare sequence diagrams of the rest api

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#19]

**Comment by muatik** [comment]
While designing sequence diagrams, we can easily see the components in the system, and especially their interactions with each other. The REST API is the endpoint that simply defines the essential functions of the software system, which can be thought of a black back, to the outside world. In addition, after designing the sequence diagrams, we can start to implement or at leat plan the web front-end application, the native mobile application, and maybe other clients.

I propose using websequencediagrams.com since we could simply save them in plain text format too, in addition to image format.

**Comment by muatik** [comment]
depends on #21

**Comment by fkucuk** [comment]
I've looked at websequencediagrams, it's cute but I've preferred draw.io to create the first sequence diagram.

![image](https://raw.githubusercontent.com/SWE574-Groupago/heritago/master/diagrams/Sequence%20Diagram%2001.png)
