### ISSUE TITLE
build a prototype template to enable annotation on an image

### ISSUE THREAD

**Issue by kartalerkoc** [SWE574-RenameMe/swe574-CoolName#48]
It is crucial to build a prototype using a blank page, an image at first and implementing necessary frameworks to understand how we will enable users to interact with the images. While interacting with images for annotation purposes, it is vital to have selectors for regions, point, different geometrical shapes such as polygon, triangle, circle, ellips, rectangle. Assigned to @sanal-cem

**Comment by sanal-cem** [comment]
- [VGG Image Annotator (VIA)](http://www.robots.ox.ac.uk/~vgg/software/via/) is used for creating an image annotation prototype. That protoype includes sending the filename from Create-Heritage-Item-Form page to Create-Image-Annotation page. These front end pages are not real, they are also prototypes.
- In order to test that prototype, these steps should be followed. Open annot.html, select the visible image, you should be forwarded to the image annotation page. Image file should be selected from the menu, Image -> Load or Add Images section.
- There is a development problem. For fetching and annotating the image in Create-Image-Annotation page, the input file could not be given as blob data instead of selecting it via <input type="file" ...> element. Moreover, the file should be given after _via_init() function execution. sel_local_images() function should get an invisible_file_input object. After solving that problem, the prototype should be developed incrementally.

**Comment by muatik** [comment]
I am going to modify VGG's source code in order to make it more flexible so that we can make any images annotation-enabled and get annotation data either through callbacks or events. 

@kartalerkoc Which functionalities do we need?
For instace, we can give an image <img> element to allow users make selections on the image as follows:
```
ImageSelector.init(image_element, {
  onNewSelectionDone: function(data) {....},
  onSelectionChanged: function(data) {....},
  onSelectionDeleted: function(data) {....},
});
````

And we can create some methods that we need, for instace:
```
var list = ImageSelector.getAllSelections(...);
var list = ImageSelector.removeAllSelections(...);
ImageSelector.applySelections(selectionList);
```

**Comment by kartalerkoc** [comment]
The modal that will be prepared in #83 depends on this. This issue is under Milestone FE2 now.
